name = "aether-realist"
main = "src/worker.js"
compatibility_date = "2024-02-06"
workers_dev = true

[build]
command = ""

[compatibility_flags]
nodejs_compat = true

[vars]
SECRET_PATH = "/v1/api/sync"
